"""Initial migration

Revision ID: 5dcb21398ba9
Revises: 
Create Date: 2026-02-21 11:33:51.293775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dcb21398ba9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_register_closes',
    sa.Column('close_date', sa.Date(), nullable=False),
    sa.Column('closed_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_cash', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_pos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_bank_transfer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_check', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_other', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payments_count', sa.Integer(), nullable=False),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('close_date')
    )
    op.create_table('clients',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=True),
    sa.Column('is_company', sa.Boolean(), nullable=False),
    sa.Column('tax_id', sa.String(length=16), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('province', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_foreign', sa.Boolean(), nullable=False),
    sa.Column('sdi_code', sa.String(length=7), nullable=True),
    sa.Column('pec', sa.String(length=255), nullable=True),
    sa.Column('vat_regime', sa.String(length=5), nullable=True),
    sa.Column('vat_exemption', sa.Boolean(), nullable=False),
    sa.Column('vat_exemption_code', sa.String(length=10), nullable=True),
    sa.Column('vat_exemption_reason', sa.String(length=255), nullable=True),
    sa.Column('split_payment', sa.Boolean(), nullable=False),
    sa.Column('default_vat_rate', sa.Float(), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('payment_method_default', sa.String(length=20), nullable=True),
    sa.Column('default_discount_percent', sa.Float(), nullable=True),
    sa.Column('billing_address', sa.String(length=255), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=True),
    sa.Column('billing_zip_code', sa.String(length=10), nullable=True),
    sa.Column('billing_province', sa.String(length=10), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('credit_limit_action', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_index('ix_clients_foreign_vat_exemption', 'clients', ['is_foreign', 'vat_exemption'], unique=False)
    op.create_index('ix_clients_name_surname', 'clients', ['name', 'surname'], unique=False)
    op.create_index('ix_clients_sdi_code', 'clients', ['sdi_code'], unique=False)
    op.create_index('ix_clients_tax_id', 'clients', ['tax_id'], unique=False)
    op.create_table('part_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['part_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_categories_parent_id'), 'part_categories', ['parent_id'], unique=False)
    op.create_table('technicians',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intent_declarations',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('protocol_number', sa.String(length=50), nullable=False),
    sa.Column('declaration_date', sa.Date(), nullable=False),
    sa.Column('amount_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('used_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_intent_declarations_active', 'intent_declarations', ['client_id', 'is_active'], unique=False)
    op.create_index('ix_intent_declarations_client_id', 'intent_declarations', ['client_id'], unique=False)
    op.create_index('ix_intent_declarations_expiry_date', 'intent_declarations', ['expiry_date'], unique=False)
    op.create_table('parts',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('compatible_models', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('min_stock_level', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['part_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parts_active_stock', 'parts', ['is_active', 'stock_quantity'], unique=False)
    op.create_index(op.f('ix_parts_brand'), 'parts', ['brand'], unique=False)
    op.create_index(op.f('ix_parts_category_id'), 'parts', ['category_id'], unique=False)
    op.create_index(op.f('ix_parts_code'), 'parts', ['code'], unique=True)
    op.create_index(op.f('ix_parts_is_active'), 'parts', ['is_active'], unique=False)
    op.create_table('payments',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash', 'pos', 'bank_transfer', 'check', 'other')", name='ck_payments_payment_method'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_client_id', 'payments', ['client_id'], unique=False)
    op.create_index('ix_payments_payment_date', 'payments', ['payment_date'], unique=False)
    op.create_table('vehicles',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('current_km', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate'),
    sa.UniqueConstraint('vin')
    )
    op.create_index('ix_vehicles_client_plate', 'vehicles', ['client_id', 'plate'], unique=False)
    op.create_index('ix_vehicles_plate', 'vehicles', ['plate'], unique=False)
    op.create_index('ix_vehicles_vin', 'vehicles', ['vin'], unique=False)
    op.create_table('stock_movements',
    sa.Column('part_id', sa.Uuid(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("movement_type IN ('in', 'out', 'adjustment')", name='ck_stock_movements_type'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stock_movements_part_id'), 'stock_movements', ['part_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_technician_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('problem_description', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('km_in', sa.Integer(), nullable=True),
    sa.Column('km_out', sa.Integer(), nullable=True),
    sa.Column('estimated_delivery', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'in_progress', 'waiting_parts', 'completed', 'invoiced', 'cancelled')", name='ck_work_orders_status'),
    sa.CheckConstraint('(km_out IS NULL OR km_in IS NULL OR km_out >= km_in)', name='ck_work_orders_km'),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['technicians.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_assigned_technician_id'), 'work_orders', ['assigned_technician_id'], unique=False)
    op.create_index(op.f('ix_work_orders_client_id'), 'work_orders', ['client_id'], unique=False)
    op.create_index('ix_work_orders_status', 'work_orders', ['status'], unique=False)
    op.create_index('ix_work_orders_status_created', 'work_orders', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_work_orders_vehicle_id'), 'work_orders', ['vehicle_id'], unique=False)
    op.create_table('invoices',
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('bill_to_client_id', sa.Uuid(), nullable=True),
    sa.Column('bill_to_name', sa.String(length=255), nullable=True),
    sa.Column('bill_to_tax_id', sa.String(length=50), nullable=True),
    sa.Column('bill_to_address', sa.Text(), nullable=True),
    sa.Column('claim_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stamp_duty_applied', sa.Boolean(), nullable=False),
    sa.Column('stamp_duty_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_iban', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('vat_exemption', sa.Boolean(), nullable=False),
    sa.Column('vat_exemption_code', sa.String(length=10), nullable=True),
    sa.Column('split_payment', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('subtotal >= 0', name='ck_invoices_subtotal_positive'),
    sa.CheckConstraint('total >= 0', name='ck_invoices_total_positive'),
    sa.CheckConstraint('vat_amount >= 0', name='ck_invoices_vat_amount_positive'),
    sa.CheckConstraint('vat_rate >= 0', name='ck_invoices_vat_rate_positive'),
    sa.ForeignKeyConstraint(['bill_to_client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('work_order_id')
    )
    op.create_index('ix_invoices_client_id', 'invoices', ['client_id'], unique=False)
    op.create_index('ix_invoices_date_number', 'invoices', ['invoice_date', 'invoice_number'], unique=False)
    op.create_index('ix_invoices_due_date', 'invoices', ['due_date'], unique=False)
    op.create_index('ix_invoices_invoice_date', 'invoices', ['invoice_date'], unique=False)
    op.create_table('part_usages',
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('part_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_part_usages_quantity'),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_usages_part_id'), 'part_usages', ['part_id'], unique=False)
    op.create_index(op.f('ix_part_usages_work_order_id'), 'part_usages', ['work_order_id'], unique=False)
    op.create_table('work_order_items',
    sa.Column('work_order_id', sa.Uuid(), nullable=False),
    sa.Column('technician_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("item_type IN ('labor', 'service')", name='ck_work_order_items_item_type'),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_items_technician_id'), 'work_order_items', ['technician_id'], unique=False)
    op.create_index(op.f('ix_work_order_items_work_order_id'), 'work_order_items', ['work_order_id'], unique=False)
    op.create_table('credit_notes',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('credit_note_number', sa.String(length=20), nullable=False),
    sa.Column('credit_note_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stamp_duty_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_note_number')
    )
    op.create_table('deposits',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('work_order_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('deposit_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_lines',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('line_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("line_type IN ('labor', 'service', 'part')", name='ck_invoice_lines_line_type'),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name='ck_invoice_lines_discount_percent'),
    sa.CheckConstraint('quantity > 0', name='ck_invoice_lines_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_invoice_lines_unit_price_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_index('ix_invoice_lines_invoice_number', 'invoice_lines', ['invoice_id', 'line_number'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_allocation_amount_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_allocation_invoice', 'payment_allocations', ['invoice_id'], unique=False)
    op.create_index('idx_payment_invoice_unique', 'payment_allocations', ['payment_id', 'invoice_id'], unique=True)
    op.create_table('credit_note_lines',
    sa.Column('credit_note_id', sa.Uuid(), nullable=False),
    sa.Column('line_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_note_lines')
    op.drop_index('idx_payment_invoice_unique', table_name='payment_allocations')
    op.drop_index('idx_allocation_invoice', table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index('ix_invoice_lines_invoice_number', table_name='invoice_lines')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_table('deposits')
    op.drop_table('credit_notes')
    op.drop_index(op.f('ix_work_order_items_work_order_id'), table_name='work_order_items')
    op.drop_index(op.f('ix_work_order_items_technician_id'), table_name='work_order_items')
    op.drop_table('work_order_items')
    op.drop_index(op.f('ix_part_usages_work_order_id'), table_name='part_usages')
    op.drop_index(op.f('ix_part_usages_part_id'), table_name='part_usages')
    op.drop_table('part_usages')
    op.drop_index('ix_invoices_invoice_date', table_name='invoices')
    op.drop_index('ix_invoices_due_date', table_name='invoices')
    op.drop_index('ix_invoices_date_number', table_name='invoices')
    op.drop_index('ix_invoices_client_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_work_orders_vehicle_id'), table_name='work_orders')
    op.drop_index('ix_work_orders_status_created', table_name='work_orders')
    op.drop_index('ix_work_orders_status', table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_client_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_assigned_technician_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_stock_movements_part_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_type'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index('ix_vehicles_vin', table_name='vehicles')
    op.drop_index('ix_vehicles_plate', table_name='vehicles')
    op.drop_index('ix_vehicles_client_plate', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_payments_payment_date', table_name='payments')
    op.drop_index('ix_payments_client_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_parts_is_active'), table_name='parts')
    op.drop_index(op.f('ix_parts_code'), table_name='parts')
    op.drop_index(op.f('ix_parts_category_id'), table_name='parts')
    op.drop_index(op.f('ix_parts_brand'), table_name='parts')
    op.drop_index('ix_parts_active_stock', table_name='parts')
    op.drop_table('parts')
    op.drop_index('ix_intent_declarations_expiry_date', table_name='intent_declarations')
    op.drop_index('ix_intent_declarations_client_id', table_name='intent_declarations')
    op.drop_index('ix_intent_declarations_active', table_name='intent_declarations')
    op.drop_table('intent_declarations')
    op.drop_table('technicians')
    op.drop_index(op.f('ix_part_categories_parent_id'), table_name='part_categories')
    op.drop_table('part_categories')
    op.drop_index('ix_clients_tax_id', table_name='clients')
    op.drop_index('ix_clients_sdi_code', table_name='clients')
    op.drop_index('ix_clients_name_surname', table_name='clients')
    op.drop_index('ix_clients_foreign_vat_exemption', table_name='clients')
    op.drop_table('clients')
    op.drop_table('cash_register_closes')
    # ### end Alembic commands ###
